name: Flask Docker Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      LLM_MODEL: ${{ secrets.LLM_MODEL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and start services
      working-directory: ./flask
      run: |
        docker compose up -d

    - name: Install python dependencies
      working-directory: ./flask
      run: |
        pip install -r requirements.txt
        
    - name: Run tests
      working-directory: ./flask
      run: |
        python llm_test.py

    - name: Shut down services
      working-directory: ./flask
      run: docker-compose down
