name: Flask Docker Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and start services
      working-directory: ./flask
      run: |
        docker-compose up -d --build

    - name: Run tests
      working-directory: ./flask
      run: |
        python llm-test.py

    - name: Shut down services
      working-directory: ./flask
      run: docker-compose down
